import styles from "@/styles/Home.module.css";
import { DefaultLayout } from "@/src/layouts";
import Head from "next/head";
import type { ReactElement } from "react";
import type { NextPageWithLayout } from "./_app";
import { ParagraphGroup } from "@/src/components";
import Image1 from "@/src/assets/images/Item1.png";
import Image2 from "@/src/assets/images/Item2.png";
import Image3 from "@/src/assets/images/Item3.png";

const News: NextPageWithLayout = () => {
  const paragraphs = [
    {
      src: Image1,
      title: "Lorem ipsum dolor sit asmet?",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non dui sodales, faucibus libero ut, posuere felis. Donec imperdiet suscipit accumsan. Aenean consequat condimentum velit ut tempor. Nam porta massa in metus bibendum congue. Pellentesque ultrices liquam egestas nunc at ullamcorper ultricies. Donec feugiat velit nulla, vel sodales est ullamcorper id. Aenean consequat condimentum velit ut tempor. Nam porta massa in metus bibendum congue. Pellentesque ultrices vestibulum mattis.",
    },
    {
      src: Image2,
      title: "Lorem ipsum dolor sit asmet?",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non dui sodales, faucibus libero ut, posuere felis. Donec imperdiet suscipit accumsan. Aenean consequat condimentum velit ut tempor. Nam porta massa in metus bibendum congue. Pellentesque ultrices liquam egestas nunc at ullamcorper ultricies. Donec feugiat velit nulla, vel sodales est ullamcorper id. Aenean consequat condimentum velit ut tempor. Nam porta massa in metus bibendum congue. Pellentesque ultrices vestibulum mattis.",
    },
    {
      src: Image3,
      title: "Lorem ipsum dolor sit asmet?",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non dui sodales, faucibus libero ut, posuere felis. Donec imperdiet suscipit accumsan. Aenean consequat condimentum velit ut tempor. Nam porta massa in metus bibendum congue. Pellentesque ultrices liquam egestas nunc at ullamcorper ultricies. Donec feugiat velit nulla, vel sodales est ullamcorper id. Aenean consequat condimentum velit ut tempor. Nam porta massa in metus bibendum congue. Pellentesque ultrices vestibulum mattis.",
    },
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.wrapper}>
        <div className={`${styles.inner} `}>
          <div className={`${styles.logo}`}></div>
        </div>
        <div
          className={`${styles.inner}`}
          style={{
            background: "#EFEFEF",
          }}
        >
          <div className={styles.description}>
            <p className={`text_normal bold`}>Lorem ipsum dolor sit asmet?</p>
            <p className={`text_small`}>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
              tristique consequat placerat. Vestibulum auctor pellentesque sem,
              eu posuere erat hendrerit quis. Maecenas vel consequat turpis. Nam
              facilisis, ligula in mattis sodales, augue justo tristique nulla,
              sed lacinia ante eros ut mi. Morbi vitae diam augue. Aliquam vel
              mauris a nibh auctor commodo. Praesent et nisi eu justo eleifend
              convallis. Quisque suscipit maximus vestibulum. Phasellus congue
              mollis orci, sit amet luctus augue tristique eu. Donec vulputate
              odio neque, sed semper turpis pellentesque a.
            </p>
          </div>
        </div>
        <div className={`${styles.inner} ${styles.parasGrid}`}>
          {paragraphs &&
            paragraphs.map((item, index) => (
              <ParagraphGroup
                image={item.src}
                title={item.title}
                text={item.content}
                key={index}
              />
            ))}
        </div>
      </main>
    </>
  );
};

News.getLayout = function getLayout(page: ReactElement) {
  return <DefaultLayout>{page}</DefaultLayout>;
};

export default News;
